EXEC "pqact"

# Only allow local connections for LDM-7 relay (not needed for our simple setup)
ALLOW ANY ^((localhost|loopback)|(127\.0\.0\.1\.?))$

# Request global METAR/SPECI bulletins from IEM
REQUEST IDS|DDPLUS "^S[AP]" mesonet-ah.agron.iastate.edu
